name: Fred Hutch Girls Who Code
description: Fred Hutch Girls Who Code club
url: ""

markdown: kramdown
permalink: /:categories/:title/
future: true

redcarpet:
  extensions:
   - tables
   - no_intra_emphasis
   - autolink
   - superscript
   - strikethrough

collections:
  facilitators:
      output: true
  weekly_links:
    output: true

exclude: ['README.markdown', 'Gemfile.lock', 'Gemfile']
